import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import { Providers } from "./providers";
import { Footer } from "@/components/Footer";
import MenuBar from "@/components/MenuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            {/* <Sidebar /> */}
            <MenuBar child={children} />
            {/* <div className="max-w-6xl p-2 sm:p-4 sm:px-10 mx-auto ">
              {children}
            </div> */}
            {/* <Footer /> */}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
